title: ENUSEC Blog
author: ENUSEC
email: team@enusec.org
description: > # this means to ignore newlines until "show_exerpts:"
  The Official ENUSEC (Edinburgh Napier Security Society) Research Blog.
  Read about our research, vulnerabilities, CTF Writeups and quality content our members produce.
show_excerpts: true # set to true to show excerpts on the homepage
baseurl:

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
sass:
  sass_dir: _sass

permalink: /posts/:title/
texture:
  title: ENUSEC
  tagline: Edinburgh Napier Security Society
  date_format: "%b %-d, %Y"
  style: enusec
  showNav: true
  navigation:
    - title: "Home"
      url: "/"
    - title: "About"
      url: "/about"
    - title: "Membership"
      url: "https://join.enusec.org"
    - title: "Discord"
      url: "https://discord.enusec.org"
  showPicker: false

  # generate social links in footer
  social_links:
    twitter: enusec
    github:  ENUSEC
    linkedIn: enusec
 

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
#  - about.md

# Build settings
# theme: texture

plugins:
  - jekyll-seo-tag
#  - jekyll-feed
