title:              ENUSEC Blog
email:              team@enusec.org
description:        Edinburgh Napier Security Society Research Blog
author:             ENUSEC
baseurl:            "/"
url:                "https://blog.enusec.org"

# Social Profiles
twitter_username:   enusec
github_username:    ENUSEC
facebook_username:  enusec
instagram_username:  
linkedin_username:

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
